version: '3.8'

services:
  # Main Database (MySQL)
  db-main:
    image: mysql:8.0
    container_name: database-presensi
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DEV_MAIN_PASSWORD}
      MYSQL_DATABASE: ${DEV_MAIN_DATABASE}
      MYSQL_USER: ${DEV_MAIN_USERNAME}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  # API Application
  api:
    build: .
    container_name: api_absensi_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
      - /app/node_modules
      - ./:/app

    depends_on:
      - db-main


volumes:
  db_data:


